<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Server">
      <HintPath>..\Server\bin\Release\net6.0\win-x64\Server.dll</HintPath>
    </Reference>
    <Reference Include="Lidgren.Network">
      <HintPath>..\Server\bin\Release\net6.0\win-x64\Lidgren.Network.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
