<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net4.8</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lidgren.Network" Version="1.0.2" />
    <Compile Include="../Common/*.cs" />

    <Reference Include="C:\Program Files (x86)\Steam\steamapps\common\Spaceflight Simulator\Spaceflight Simulator Game\Spaceflight Simulator_Data\Managed/*">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Spaceflight Simulator\Spaceflight Simulator Game\Spaceflight Simulator_Data\Managed\*.dll</HintPath>
    </Reference>
    <Reference Include="UITools">
      <HintPath>C:\Users\Administrator\Downloads\SFSs\1.5.10.2_Release\Mods\UITools\UITools.dll</HintPath>
    </Reference>

    <!-- ? The following DLLs cause warnings on build -->
    <Reference Remove="**/System.IO.Compression.dll" />
    <Reference Remove="**/System.Net.Http.dll" />
    <Reference Remove="**/Firebase.*.dll" />
    <Reference Remove="**/Unity.Compat.dll" />
    <Reference Remove="**/Unity.Tasks.dll" />
    
    <!-- ? Exclude conflicting System assemblies to resolve Queue<T> ambiguity -->
    <Reference Remove="**/System.dll" />
    <Reference Remove="**/System.Core.dll" />
    <Reference Remove="**/System.Runtime.dll" />
    <Reference Remove="**/System.Runtime.CompilerServices.Unsafe.dll" />
  </ItemGroup>
</Project>